<?php
require_once dirname(__DIR__).'/includes/site.php';
$products=db()->query("SELECT * FROM products WHERE status='published' ORDER BY sort_order,id LIMIT 3")->fetchAll();
$posts=db()->query("SELECT * FROM posts WHERE status='published' ORDER BY published_at DESC,id DESC LIMIT 3")->fetchAll();
$phone=setting('phone','9693830075'); site_header('Home','Premium Power Cement - high-quality PPC cement for durable construction.');
?><main><section class="home-hero"><div class="container hero-layout"><div class="hero-message"><span class="hero-label">PORTLAND POZZOLANA CEMENT · PPC</span><h1>Premium Power Cement.<br><em>The Strength Behind Every Landmark.</em></h1><p>Quality cement engineered for strong, durable and long-lasting residential, commercial and infrastructure construction.</p><div class="hero-actions"><a class="btn" href="dealer.php">Become a Dealer</a><a class="btn light-btn" href="downloads/premium-cement.pdf" download>Download Brochure</a></div><div class="hero-contact">Product & bulk supply enquiry: <a href="tel:+91<?=$phone?>">+91 <?=e($phone)?></a></div></div><div class="hero-product"><div class="product-glow"></div><img src="uploads/premium-products.jpg" alt="Premium Power Cement product range"><span class="quality-seal">QUALITY<br>ASSURED</span></div></div></section>
<section class="promise-bar"><div class="container promise-grid"><div><b>ISO 9001:2015</b><span>Quality-focused process</span></div><div><b>50 KG</b><span>Standard packaging</span></div><div><b>PPC Cement</b><span>Durable construction</span></div><div><b>Dealer Support</b><span>Responsive supply service</span></div></div></section>
<section class="section intro-section"><div class="container split"><div class="visual-panel"><img src="uploads/premium-products.jpg" alt="Premium Group Cement bags"><div class="visual-note"><strong>Strong Cement</strong><span>Strong Trust</span></div></div><div><div class="eyebrow">About Premium Group Cement</div><h2 class="title">Quality materials for foundations that last</h2><p class="lead">We supply dependable cement solutions for homes, businesses and infrastructure projects with a firm focus on consistency, value and service.</p><p>Our objective is simple: deliver quality cement at the right price while building honest, long-term relationships with customers, builders, dealers and partners.</p><div class="mini-points"><span>✓ Consistent quality</span><span>✓ Customer support</span><span>✓ Timely supply</span><span>✓ Competitive value</span></div><a class="text-link arrow-link" href="about.php">Learn more about Premium Group <b>→</b></a></div></div></section>
<section class="section product-showcase"><div class="container"><div class="section-heading"><div><div class="eyebrow">Our Product Range</div><h2 class="title">Engineered for dependable performance</h2></div><a class="text-link" href="products.php">View all products →</a></div><div class="premium-product-grid"><?php foreach($products as $i=>$p):?><article class="premium-product-card"><div class="product-media"><span class="product-index">0<?=$i+1?></span><img src="<?=$p['featured_image']?UPLOAD_URL.e($p['featured_image']):'uploads/premium-products.jpg'?>" alt="<?=e($p['name'])?>"></div><div class="product-info"><span>PPC · 50 KG</span><h3><?=e($p['name'])?></h3><p><?=e($p['description'])?></p><a href="product.php?product=<?=e($p['slug'])?>">Explore product <b>→</b></a></div></article><?php endforeach?></div></div></section>
<section class="section strength-section"><div class="container"><div class="strength-head"><div><div class="eyebrow">Why Premium Power Cement</div><h2>Strength you can build on.<br>Service you can rely on.</h2></div><p>From product consistency to dealer support, our approach is centred on making quality cement accessible and dependable.</p></div><div class="strength-grid"><article><span>01</span><h3>High Compressive Strength</h3><p>Designed to support strong and durable construction performance.</p></article><article><span>02</span><h3>Strict Quality Control</h3><p>Quality-led processes focused on consistency across every bag.</p></article><article><span>03</span><h3>Improved Workability</h3><p>Suitable for concrete, masonry and smooth finishing applications.</p></article><article><span>04</span><h3>Distribution Support</h3><p>Responsive coordination for dealers, contractors and bulk buyers.</p></article></div></div></section>
<section class="section applications"><div class="container"><div class="eyebrow">Built For Every Need</div><h2 class="title">From homes to landmark projects</h2><div class="application-grid"><div><b>Residential</b><span>Homes, apartments and foundations</span></div><div><b>Commercial</b><span>Offices, complexes and institutions</span></div><div><b>RCC Work</b><span>Slabs, columns and structural elements</span></div><div><b>Finishing</b><span>Plastering, masonry and general work</span></div></div></div></section>
<section class="dealer-banner"><div class="container dealer-layout"><div><span class="hero-label">DEALER & DISTRIBUTOR NETWORK</span><h2>Build a stronger business with Premium Power Cement.</h2><p>Join our growing network with a high-demand product, attractive opportunity, marketing coordination and supply support.</p></div><div><a class="btn" href="dealer.php">Submit Dealer Inquiry</a><a class="dealer-phone" href="tel:+91<?=$phone?>">or call +91 <?=e($phone)?></a></div></div></section>
<?php if($posts):?><section class="section blog-preview"><div class="container"><div class="section-heading"><div><div class="eyebrow">Knowledge Center</div><h2 class="title">Latest updates & construction tips</h2></div><a class="text-link" href="blog.php">View all articles →</a></div><div class="grid"><?php foreach($posts as $p):?><article class="card blog-card"><?php if($p['featured_image']):?><img src="<?=UPLOAD_URL.e($p['featured_image'])?>" alt="<?=e($p['title'])?>"><?php endif?><div class="card-body"><small><?=date('d M Y',strtotime($p['published_at']))?></small><h3><?=e($p['title'])?></h3><p><?=e($p['excerpt'])?></p><a class="text-link" href="post.php?slug=<?=e($p['slug'])?>">Read article →</a></div></article><?php endforeach?></div></div></section><?php endif?>
<section class="section faq-section"><div class="container faq-layout"><div><div class="eyebrow">Common Questions</div><h2 class="title">Everything you need to know</h2><p>Need pricing or product guidance? Our team is ready to assist.</p><a class="text-link" href="contact.php">Contact our team →</a></div><div class="faq"><details open><summary>What type of cement does Premium Group supply?</summary><p>Our range focuses on Portland Pozzolana Cement (PPC) in standard 50 KG packaging.</p></details><details><summary>How can I apply for dealership?</summary><p>Submit the Dealer form and our team will contact you.</p></details><details><summary>Can I request bulk supply pricing?</summary><p>Yes. Select Bulk Supply on Contact or call our office number.</p></details><details><summary>Where can I download product information?</summary><p>The product brochure is available from the homepage.</p></details></div></div></section></main><?php site_footer();
