CREATE DATABASE IF NOT EXISTS cement_cms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cement_cms;
CREATE TABLE users(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('super_admin','admin','editor') NOT NULL DEFAULT 'editor',status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE pages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,type ENUM('page','service','project','team') NOT NULL DEFAULT 'page',excerpt TEXT,content LONGTEXT,featured_image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',sort_order INT DEFAULT 0,meta_title VARCHAR(190),meta_description VARCHAR(320),created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE posts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,excerpt TEXT,content LONGTEXT,featured_image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',meta_title VARCHAR(190),meta_description VARCHAR(320),author_id BIGINT UNSIGNED NULL,published_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE media(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190),file_name VARCHAR(255) NOT NULL,alt_text VARCHAR(255),media_type ENUM('image','banner','document') DEFAULT 'image',created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE enquiries(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(20),subject VARCHAR(160) NOT NULL,message TEXT NOT NULL,status ENUM('new','read','replied','closed') DEFAULT 'new',ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE settings(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(120) NOT NULL UNIQUE,setting_value TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO settings(setting_key,setting_value) VALUES ('site_name','CemCore Industries'),('hero_title','Building Tomorrow on Stronger Foundations'),('hero_text','High-performance cement for homes, infrastructure and industry.'),('home_meta_title','CemCore Industries | Premium Cement Solutions'),('home_meta_description','Reliable cement products engineered for durable construction.'),('phone','+91 98765 43210'),('email','info@cemcore.example'),('address','Industrial Area, India');
-- Generate a secure password hash with: php -r "echo password_hash('ChangeMe123!', PASSWORD_DEFAULT);"
-- Then insert your first account:
-- INSERT INTO users(name,email,password_hash,role) VALUES('Administrator','admin@example.com','PASTE_HASH_HERE','super_admin');

