<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/functions.php'; require_admin();
$section=$_GET['section']??'dashboard'; $allowed=['dashboard','pages','products','posts','media','enquiries','users','settings','profile'];
if(!in_array($section,$allowed,true))$section='dashboard';

function go(string $section,string $message):never{flash('ok',$message);redirect('/admin/index.php?section='.$section);}
function val(string $key):string{return trim((string)($_POST[$key]??''));}
function delete_uploaded(?string $name):void{if($name&&preg_match('/^[a-zA-Z0-9._-]+$/',$name)){ $path=UPLOAD_DIR.$name;if(is_file($path))@unlink($path);}}

try{
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=val('action');
 if($action==='save_page'){$id=(int)($_POST['id']??0);$img=upload_image('featured_image');$d=[val('title'),slugify(val('slug')?:val('title')),val('type'),val('excerpt'),val('content'),val('status'),(int)($_POST['sort_order']??0),val('meta_title'),val('meta_description')];if($id){$sql='UPDATE pages SET title=?,slug=?,type=?,excerpt=?,content=?,status=?,sort_order=?,meta_title=?,meta_description=?'.($img?',featured_image=?':'').' WHERE id=?';if($img)$d[]=$img;$d[]=$id;}else{$sql='INSERT INTO pages(title,slug,type,excerpt,content,status,sort_order,meta_title,meta_description,featured_image,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)';$d[]=$img;$d[]=$_SESSION['admin_id'];}db()->prepare($sql)->execute($d);go('pages','Content saved successfully.');}
 if($action==='delete_page'){require_role(['super_admin','admin']);db()->prepare('DELETE FROM pages WHERE id=?')->execute([(int)$_POST['id']]);go('pages','Content deleted.');}
 if($action==='save_product'){$id=(int)($_POST['id']??0);$img=upload_image('featured_image');$d=[val('name'),slugify(val('slug')?:val('name')),val('tagline'),val('description'),val('features'),val('applications'),val('status'),(int)($_POST['sort_order']??0),val('meta_title'),val('meta_description')];if($id){$sql='UPDATE products SET name=?,slug=?,tagline=?,description=?,features=?,applications=?,status=?,sort_order=?,meta_title=?,meta_description=?'.($img?',featured_image=?':'').' WHERE id=?';if($img)$d[]=$img;$d[]=$id;}else{$sql='INSERT INTO products(name,slug,tagline,description,features,applications,status,sort_order,meta_title,meta_description,featured_image) VALUES(?,?,?,?,?,?,?,?,?,?,?)';$d[]=$img;}db()->prepare($sql)->execute($d);go('products','Product saved successfully.');}
 if($action==='delete_product'){require_role(['super_admin','admin']);db()->prepare('DELETE FROM products WHERE id=?')->execute([(int)$_POST['id']]);go('products','Product deleted.');}
 if($action==='save_post'){$id=(int)($_POST['id']??0);$img=upload_image('featured_image');$published=val('published_at')?:date('Y-m-d H:i:s');$d=[val('title'),slugify(val('slug')?:val('title')),val('excerpt'),val('content'),val('status'),val('meta_title'),val('meta_description'),$published];if($id){$sql='UPDATE posts SET title=?,slug=?,excerpt=?,content=?,status=?,meta_title=?,meta_description=?,published_at=?'.($img?',featured_image=?':'').' WHERE id=?';if($img)$d[]=$img;$d[]=$id;}else{$sql='INSERT INTO posts(title,slug,excerpt,content,status,meta_title,meta_description,published_at,featured_image,author_id) VALUES(?,?,?,?,?,?,?,?,?,?)';$d[]=$img;$d[]=$_SESSION['admin_id'];}db()->prepare($sql)->execute($d);go('posts','Blog post saved.');}
 if($action==='delete_post'){require_role(['super_admin','admin']);db()->prepare('DELETE FROM posts WHERE id=?')->execute([(int)$_POST['id']]);go('posts','Post deleted.');}
 if($action==='upload_media'){$img=upload_image('media_file');if(!$img)throw new RuntimeException('Please choose an image.');db()->prepare('INSERT INTO media(title,file_name,alt_text,media_type,created_by) VALUES(?,?,?,?,?)')->execute([val('title'),$img,val('alt_text'),val('media_type'),$_SESSION['admin_id']]);go('media','Media uploaded.');}
 if($action==='delete_media'){require_role(['super_admin','admin']);$s=db()->prepare('SELECT file_name FROM media WHERE id=?');$s->execute([(int)$_POST['id']]);delete_uploaded($s->fetchColumn()?:null);db()->prepare('DELETE FROM media WHERE id=?')->execute([(int)$_POST['id']]);go('media','Media deleted.');}
 if($action==='enquiry_status'){db()->prepare('UPDATE enquiries SET status=? WHERE id=?')->execute([val('status'),(int)$_POST['id']]);go('enquiries','Enquiry status updated.');}
 if($action==='delete_enquiry'){require_role(['super_admin','admin']);db()->prepare('DELETE FROM enquiries WHERE id=?')->execute([(int)$_POST['id']]);go('enquiries','Enquiry deleted.');}
 if($action==='save_user'){require_role(['super_admin']);$id=(int)($_POST['id']??0);if($id){$d=[val('name'),strtolower(val('email')),val('role'),val('status')];$sql='UPDATE users SET name=?,email=?,role=?,status=?'.(val('password')?',password_hash=?':'').' WHERE id=?';if(val('password'))$d[]=password_hash(val('password'),PASSWORD_DEFAULT);$d[]=$id;}else{if(strlen(val('password'))<8)throw new RuntimeException('Password must be at least 8 characters.');$sql='INSERT INTO users(name,email,password_hash,role,status) VALUES(?,?,?,?,?)';$d=[val('name'),strtolower(val('email')),password_hash(val('password'),PASSWORD_DEFAULT),val('role'),val('status')];}db()->prepare($sql)->execute($d);go('users','User account saved.');}
 if($action==='delete_user'){require_role(['super_admin']);$id=(int)$_POST['id'];if($id===(int)$_SESSION['admin_id'])throw new RuntimeException('You cannot delete your own account.');db()->prepare('DELETE FROM users WHERE id=?')->execute([$id]);go('users','User deleted.');}
 if($action==='save_settings'){require_role(['super_admin','admin']);foreach((array)($_POST['settings']??[]) as $k=>$v){if(!preg_match('/^[a-z0-9_]+$/',$k))continue;db()->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)')->execute([$k,trim((string)$v)]);}go('settings','Website settings updated.');}
 if($action==='change_password'){$s=db()->prepare('SELECT password_hash FROM users WHERE id=?');$s->execute([$_SESSION['admin_id']]);if(!password_verify(val('current_password'),(string)$s->fetchColumn()))throw new RuntimeException('Current password is incorrect.');if(strlen(val('new_password'))<8||val('new_password')!==val('confirm_password'))throw new RuntimeException('New passwords must match and contain at least 8 characters.');db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash(val('new_password'),PASSWORD_DEFAULT),$_SESSION['admin_id']]);go('profile','Password changed successfully.');}
}}
catch(Throwable $e){flash('error',$e->getMessage());redirect('/admin/index.php?section='.$section);}

$counts=['Pages'=>(int)db()->query('SELECT COUNT(*) FROM pages')->fetchColumn(),'Products'=>(int)db()->query('SELECT COUNT(*) FROM products')->fetchColumn(),'Posts'=>(int)db()->query('SELECT COUNT(*) FROM posts')->fetchColumn(),'New Enquiries'=>(int)db()->query("SELECT COUNT(*) FROM enquiries WHERE status='new'")->fetchColumn()];
$edit=null;if(isset($_GET['edit'])){$map=['pages'=>'pages','products'=>'products','posts'=>'posts','users'=>'users'];if(isset($map[$section])){$s=db()->prepare('SELECT * FROM '.$map[$section].' WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;}}
$nav=['dashboard'=>['⌂','Dashboard'],'pages'=>['▤','Pages & Content'],'products'=>['▣','Products'],'posts'=>['✎','Blog Posts'],'media'=>['▧','Media & Banners'],'enquiries'=>['✉','Enquiries'],'users'=>['♙','Users & Roles'],'settings'=>['⚙','Website Settings'],'profile'=>['●','My Account']];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($nav[$section][1])?> | Premium CMS</title><link rel="stylesheet" href="<?=BASE_URL?>/admin/admin.css"></head><body><div class="admin-shell"><aside class="sidebar"><div class="admin-logo"><img src="<?=BASE_URL?>/public/uploads/premium-logo.png"><div><b>PREMIUM CMS</b><small>Control Center</small></div></div><nav><?php foreach($nav as $k=>$n):if($k==='users'&&($_SESSION['admin_role']??'')!=='super_admin')continue;?><a class="<?=$section===$k?'active':''?>" href="?section=<?=$k?>"><span><?=$n[0]?></span><?=$n[1]?></a><?php endforeach?></nav><a class="logout" href="logout.php">↪ Sign out</a></aside><main class="workspace"><header class="admin-top"><button class="hamburger" onclick="document.querySelector('.sidebar').classList.toggle('show')">☰</button><div><h1><?=e($nav[$section][1])?></h1><p>Manage Premium Group Cement website</p></div><div class="account"><span><?=e(strtoupper(substr($_SESSION['admin_name'],0,1)))?></span><div><b><?=e($_SESSION['admin_name'])?></b><small><?=e($_SESSION['admin_role'])?></small></div></div></header><div class="page-body"><?php if($m=flash('ok')):?><div class="notice success"><?=e($m)?></div><?php endif?><?php if($m=flash('error')):?><div class="notice error"><?=e($m)?></div><?php endif?>
<?php include __DIR__.'/sections.php'; ?>
</div></main></div><script>document.querySelectorAll('[data-confirm]').forEach(x=>x.addEventListener('submit',e=>{if(!confirm(x.dataset.confirm))e.preventDefault()}));</script></body></html>
