<?php if($section==='dashboard'): $recent=db()->query('SELECT * FROM enquiries ORDER BY id DESC LIMIT 5')->fetchAll(); ?>
<div class="metric-grid"><?php foreach($counts as $k=>$v):?><div class="metric"><span><?=number_format($v)?></span><p><?=$k?></p></div><?php endforeach?></div><div class="two-col"><section class="panel"><div class="panel-head"><h2>Recent enquiries</h2><a href="?section=enquiries">View all</a></div><?php if(!$recent):?><div class="empty">No enquiries yet.</div><?php else:?><div class="table-wrap"><table><tr><th>Name</th><th>Subject</th><th>Status</th></tr><?php foreach($recent as $r):?><tr><td><b><?=e($r['name'])?></b><small><?=e($r['phone'])?></small></td><td><?=e($r['subject'])?></td><td><span class="badge <?=$r['status']?>"><?=e($r['status'])?></span></td></tr><?php endforeach?></table></div><?php endif?></section><section class="panel quick"><h2>Quick actions</h2><a href="?section=products">＋ Add a product</a><a href="?section=posts">＋ Write a blog post</a><a href="?section=media">↑ Upload banner/image</a><a target="_blank" href="<?=BASE_URL?>/public/">↗ View live website</a></section></div>

<?php elseif($section==='pages'): $rows=db()->query('SELECT * FROM pages ORDER BY sort_order,id DESC')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2><?=$edit?'Edit content':'Add page/content'?></h2></div><form class="cms-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_page"><input type="hidden" name="id" value="<?=$edit['id']??''?>"><div class="form-grid"><label>Title<input name="title" required value="<?=e($edit['title']??'')?>"></label><label>URL slug<input name="slug" value="<?=e($edit['slug']??'')?>" placeholder="auto-generated"></label><label>Content type<select name="type"><?php foreach(['page','service','project','team'] as $x):?><option <?=$x===($edit['type']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select></label><label>Publishing<select name="status"><option value="draft">Draft</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>Published</option></select></label><label class="wide">Short description<textarea name="excerpt" rows="2"><?=e($edit['excerpt']??'')?></textarea></label><label class="wide">Full content<textarea name="content" rows="8"><?=e($edit['content']??'')?></textarea></label><label>Featured image<input type="file" name="featured_image" accept="image/*"></label><label>Display order<input type="number" name="sort_order" value="<?=$edit['sort_order']??0?>"></label><label>SEO title<input name="meta_title" value="<?=e($edit['meta_title']??'')?>"></label><label>SEO description<textarea name="meta_description"><?=e($edit['meta_description']??'')?></textarea></label></div><button class="primary">Save content</button><?php if($edit):?><a class="secondary" href="?section=pages">Cancel</a><?php endif?></form></div><?=admin_table('pages',$rows)?>

<?php elseif($section==='products'): $rows=db()->query('SELECT * FROM products ORDER BY sort_order,id')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2><?=$edit?'Edit product':'Add product'?></h2></div><form class="cms-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_product"><input type="hidden" name="id" value="<?=$edit['id']??''?>"><div class="form-grid"><label>Product name<input name="name" required value="<?=e($edit['name']??'')?>"></label><label>URL slug<input name="slug" value="<?=e($edit['slug']??'')?>"></label><label class="wide">Tagline<input name="tagline" value="<?=e($edit['tagline']??'')?>"></label><label class="wide">Description<textarea name="description" rows="5"><?=e($edit['description']??'')?></textarea></label><label>Features (one per line)<textarea name="features" rows="7"><?=e($edit['features']??'')?></textarea></label><label>Applications (one per line)<textarea name="applications" rows="7"><?=e($edit['applications']??'')?></textarea></label><label>Product image<input type="file" name="featured_image" accept="image/*"></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>Published</option></select></label><label>Display order<input type="number" name="sort_order" value="<?=$edit['sort_order']??0?>"></label><label>SEO title<input name="meta_title" value="<?=e($edit['meta_title']??'')?>"></label><label class="wide">SEO description<textarea name="meta_description"><?=e($edit['meta_description']??'')?></textarea></label></div><button class="primary">Save product</button><?php if($edit):?><a class="secondary" href="?section=products">Cancel</a><?php endif?></form></div><?=admin_table('products',$rows)?>

<?php elseif($section==='posts'): $rows=db()->query('SELECT * FROM posts ORDER BY id DESC')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2><?=$edit?'Edit blog post':'Create blog post'?></h2></div><form class="cms-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_post"><input type="hidden" name="id" value="<?=$edit['id']??''?>"><div class="form-grid"><label>Post title<input name="title" required value="<?=e($edit['title']??'')?>"></label><label>URL slug<input name="slug" value="<?=e($edit['slug']??'')?>"></label><label class="wide">Excerpt<textarea name="excerpt"><?=e($edit['excerpt']??'')?></textarea></label><label class="wide">Article content<textarea name="content" rows="10"><?=e($edit['content']??'')?></textarea></label><label>Cover image<input type="file" name="featured_image" accept="image/*"></label><label>Publish date<input type="datetime-local" name="published_at" value="<?=!empty($edit['published_at'])?date('Y-m-d\TH:i',strtotime($edit['published_at'])):''?>"></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>Published</option></select></label><label>SEO title<input name="meta_title" value="<?=e($edit['meta_title']??'')?>"></label><label class="wide">SEO description<textarea name="meta_description"><?=e($edit['meta_description']??'')?></textarea></label></div><button class="primary">Save post</button><?php if($edit):?><a class="secondary" href="?section=posts">Cancel</a><?php endif?></form></div><?=admin_table('posts',$rows)?>

<?php elseif($section==='media'): $rows=db()->query('SELECT * FROM media ORDER BY id DESC')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2>Upload image or banner</h2><span>JPG, PNG or WebP · maximum 5 MB</span></div><form class="cms-form inline-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="upload_media"><input name="title" placeholder="Media title" required><input name="alt_text" placeholder="Image alt text"><select name="media_type"><option>image</option><option>banner</option></select><input type="file" name="media_file" accept="image/*" required><button class="primary">Upload</button></form></div><div class="media-grid"><?php foreach($rows as $r):?><article class="media-card"><img src="<?=UPLOAD_URL.e($r['file_name'])?>"><div><b><?=e($r['title'])?></b><small><?=e($r['media_type'])?></small><input readonly value="<?=UPLOAD_URL.e($r['file_name'])?>"><form method="post" data-confirm="Delete this media file?"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="delete_media"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></div></article><?php endforeach?></div>

<?php elseif($section==='enquiries'): $rows=db()->query('SELECT * FROM enquiries ORDER BY id DESC')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2>Customer & dealer enquiries</h2><span><?=count($rows)?> total</span></div><div class="table-wrap"><table><tr><th>Contact</th><th>Inquiry</th><th>Received</th><th>Status</th><th></th></tr><?php foreach($rows as $r):?><tr><td><b><?=e($r['name'])?></b><small><a href="tel:<?=e($r['phone'])?>"><?=e($r['phone'])?></a><br><?=e($r['email'])?></small></td><td><b><?=e($r['subject'])?></b><small><?=e($r['message'])?></small></td><td><?=date('d M Y',strtotime($r['created_at']))?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="enquiry_status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" onchange="this.form.submit()"><?php foreach(['new','read','replied','closed'] as $s):?><option <?=$r['status']===$s?'selected':''?>><?=$s?></option><?php endforeach?></select></form></td><td><form method="post" data-confirm="Delete this enquiry?"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="delete_enquiry"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table></div></div>

<?php elseif($section==='users'): require_role(['super_admin']);$rows=db()->query('SELECT id,name,email,role,status,created_at FROM users ORDER BY id')->fetchAll();?>
<div class="panel"><div class="panel-head"><h2><?=$edit?'Edit user':'Add CMS user'?></h2></div><form class="cms-form inline-form" method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_user"><input type="hidden" name="id" value="<?=$edit['id']??''?>"><input name="name" placeholder="Full name" required value="<?=e($edit['name']??'')?>"><input type="email" name="email" placeholder="Email" required value="<?=e($edit['email']??'')?>"><input type="password" name="password" placeholder="<?=$edit?'New password (optional)':'Password (min 8)'?>"><select name="role"><?php foreach(['super_admin','admin','editor'] as $x):?><option <?=$x===($edit['role']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select><select name="status"><option>active</option><option <?=($edit['status']??'')==='inactive'?'selected':''?>>inactive</option></select><button class="primary">Save user</button></form></div><?=admin_table('users',$rows)?>

<?php elseif($section==='settings'): $fields=['site_name'=>'Company Name','hero_title'=>'Homepage Headline','hero_text'=>'Homepage Subtitle','phone'=>'Phone','whatsapp'=>'WhatsApp Number','email'=>'Email','corporate_address'=>'Corporate Address','office_address'=>'Office Address','home_meta_title'=>'Homepage SEO Title','home_meta_description'=>'Homepage SEO Description','facebook_url'=>'Facebook URL','instagram_url'=>'Instagram URL','youtube_url'=>'YouTube URL','google_map_embed'=>'Google Map Embed URL','footer_text'=>'Footer Text'];?>
<div class="panel"><div class="panel-head"><h2>Website information & SEO</h2></div><form class="cms-form" method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_settings"><div class="form-grid"><?php foreach($fields as $k=>$label):?><label class="<?=in_array($k,['hero_text','corporate_address','office_address','home_meta_description','google_map_embed'])?'wide':''?>"><?=$label?><?php if(in_array($k,['hero_text','corporate_address','office_address','home_meta_description'])):?><textarea name="settings[<?=$k?>]"><?=e(setting($k))?></textarea><?php else:?><input name="settings[<?=$k?>]" value="<?=e(setting($k))?>"><?php endif?></label><?php endforeach?></div><button class="primary">Save website settings</button></form></div>

<?php elseif($section==='profile'):?><div class="two-col"><section class="panel"><h2>My account</h2><div class="profile-card"><div><?=e(strtoupper(substr($_SESSION['admin_name'],0,1)))?></div><h3><?=e($_SESSION['admin_name'])?></h3><span><?=e($_SESSION['admin_role'])?></span></div></section><section class="panel"><h2>Change password</h2><form class="cms-form" method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="change_password"><label>Current password<input type="password" name="current_password" required></label><label>New password<input type="password" name="new_password" minlength="8" required></label><label>Confirm password<input type="password" name="confirm_password" minlength="8" required></label><button class="primary">Change password</button></form></section></div><?php endif?>

<?php function admin_table(string $type,array $rows):string{ob_start();?><div class="panel list-panel"><div class="panel-head"><h2><?=ucfirst($type)?> list</h2><span><?=count($rows)?> records</span></div><div class="table-wrap"><table><tr><th>Name / Title</th><th>Type / Role</th><th>Status</th><th>Updated</th><th>Actions</th></tr><?php foreach($rows as $r):$title=$r['title']??$r['name']??'';?><tr><td><b><?=e($title)?></b><small><?=e($r['slug']??$r['email']??'')?></small></td><td><?=e($r['type']??$r['role']??'—')?></td><td><span class="badge <?=e($r['status']??'')?>"><?=e($r['status']??'')?></span></td><td><?=date('d M Y',strtotime($r['updated_at']??$r['created_at']))?></td><td class="actions"><a class="edit" href="?section=<?=$type?>&edit=<?=$r['id']?>">Edit</a><form method="post" data-confirm="Delete this record permanently?"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="delete_<?=rtrim($type,'s')?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table></div></div><?php return ob_get_clean();}?>
